### ISSUE TITLE
'i' being entered on lldb prompt after some actions

### ISSUE THREAD

**Issue by minego** [epheien/termdbg#1]
I just found this plugin and am loving it. I am having one small issue though where typing some commands in the lldb console works but then an 'i' is inserted.

If I switch to the debugger window and type 'n<CR>' then it does the action I expect, but then an i is inserted and I have to hit backspace before entering my next command.

**Comment by minego** [comment]
I found a work around by commenting out this line:
`call feedkeys('i', 'n')`

I don't see what that line is trying to do, but with it commented out I haven't noticed any problems.

**Comment by epheien** [comment]
I think you use vim, not nvim.
This just a bug for vim and now is fixed, please update to latest commit.

**Comment by minego** [comment]
Thank you!
