### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by kohnish** [epheien/termdbg#6]
A very nice and lean plugin.  
Would it be possible to add an licence to the repository? (preferably MIT)

**Comment by epheien** [comment]
Okay, I will deal with that later


| |
fan
|
|
***@***.***
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 12/17/2022 23:46 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [epheien/termdbg] Licence (Issue #6) |

A very nice and lean plugin.
Would it be possible to add an licence to the repository? (preferably MIT)
